/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMapperRouteImport } from './routes/_authenticated/mapper'
import { Route as AuthenticatedLedgerRouteImport } from './routes/_authenticated/ledger'
import { Route as AuthenticatedArchiveIndexRouteImport } from './routes/_authenticated/archive.index'
import { Route as AuthenticatedArchiveIdRouteImport } from './routes/_authenticated/archive.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMapperRoute = AuthenticatedMapperRouteImport.update({
  id: '/mapper',
  path: '/mapper',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLedgerRoute = AuthenticatedLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedArchiveIndexRoute =
  AuthenticatedArchiveIndexRouteImport.update({
    id: '/archive/',
    path: '/archive/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedArchiveIdRoute = AuthenticatedArchiveIdRouteImport.update({
  id: '/archive/$id',
  path: '/archive/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ledger': typeof AuthenticatedLedgerRoute
  '/mapper': typeof AuthenticatedMapperRoute
  '/archive/$id': typeof AuthenticatedArchiveIdRoute
  '/archive/': typeof AuthenticatedArchiveIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ledger': typeof AuthenticatedLedgerRoute
  '/mapper': typeof AuthenticatedMapperRoute
  '/archive/$id': typeof AuthenticatedArchiveIdRoute
  '/archive': typeof AuthenticatedArchiveIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/ledger': typeof AuthenticatedLedgerRoute
  '/_authenticated/mapper': typeof AuthenticatedMapperRoute
  '/_authenticated/archive/$id': typeof AuthenticatedArchiveIdRoute
  '/_authenticated/archive/': typeof AuthenticatedArchiveIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ledger'
    | '/mapper'
    | '/archive/$id'
    | '/archive/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/ledger' | '/mapper' | '/archive/$id' | '/archive'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/ledger'
    | '/_authenticated/mapper'
    | '/_authenticated/archive/$id'
    | '/_authenticated/archive/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mapper': {
      id: '/_authenticated/mapper'
      path: '/mapper'
      fullPath: '/mapper'
      preLoaderRoute: typeof AuthenticatedMapperRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ledger': {
      id: '/_authenticated/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof AuthenticatedLedgerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/archive/': {
      id: '/_authenticated/archive/'
      path: '/archive'
      fullPath: '/archive/'
      preLoaderRoute: typeof AuthenticatedArchiveIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/archive/$id': {
      id: '/_authenticated/archive/$id'
      path: '/archive/$id'
      fullPath: '/archive/$id'
      preLoaderRoute: typeof AuthenticatedArchiveIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedLedgerRoute: typeof AuthenticatedLedgerRoute
  AuthenticatedMapperRoute: typeof AuthenticatedMapperRoute
  AuthenticatedArchiveIdRoute: typeof AuthenticatedArchiveIdRoute
  AuthenticatedArchiveIndexRoute: typeof AuthenticatedArchiveIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedLedgerRoute: AuthenticatedLedgerRoute,
  AuthenticatedMapperRoute: AuthenticatedMapperRoute,
  AuthenticatedArchiveIdRoute: AuthenticatedArchiveIdRoute,
  AuthenticatedArchiveIndexRoute: AuthenticatedArchiveIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
